{
 "title": "Mashroom",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "95% of Requests Served Within",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mashroom_http_request_duration_seconds_bucket{service=\"Mashroom\"}[5m])) by (le)) * 1000",
     "legendFormat": "All Routes"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mashroom_http_requests_total{service=\"Mashroom\"}[5m]))",
     "legendFormat": "All Routes"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mashroom_http_requests_total{status=\"500\", service=\"Mashroom\"}[5m]))",
     "legendFormat": "HTTP 500"
    },
    {
     "expr": "sum(rate(mashroom_http_requests_total{status=\"404\", service=\"Mashroom\"}[5m]))",
     "legendFormat": "HTTP 404"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{service=\"Mashroom\"} / 1024 / 1024",
     "legendFormat": "Heap Total Node {{node}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{service=\"Mashroom\"} / 1024 / 1024",
     "legendFormat": "Heap Used Node {{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"Mashroom\"}[5m]) * 100",
     "legendFormat": "Total Node {{node}}"
    }
   ]
  },
  {
   "title": "User Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(mashroom_sessions_total{service=\"Mashroom\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Plugins",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mashroom_plugins_loaded_total{service=\"Mashroom\"}",
     "legendFormat": "Loaded Node {{node}}"
    },
    {
     "expr": "mashroom_plugins_error_total{service=\"Mashroom\"}",
     "legendFormat": "Error Node {{node}}"
    }
   ]
  },
  {
   "title": "HTTP/S Proxy Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mashroom_http_proxy_active_connections_total{service=\"Mashroom\"}",
     "legendFormat": "HTTP Active Node {{node}}"
    },
    {
     "expr": "mashroom_https_proxy_active_connections_total{service=\"Mashroom\"}",
     "legendFormat": "HTTPS Active Node {{node}}"
    }
   ]
  },
  {
   "title": "Redis Session Connected ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(mashroom_sessions_redis_nodes_connected{service=\"Mashroom\"}) by (node)",
     "legendFormat": "Node {{node}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{service=\"mashroom\",level=~\"warning|error\"}"
    }
   ]
  }
 ]
}