apiVersion: v1
kind: Namespace
metadata:
    name: lesson6
    labels:
        environment: test
        microfrontends: "true"
---
apiVersion: v1
kind: Service
metadata:
    name: microfrontend-lesson6
    namespace: lesson6
    labels:
        app: microfrontend-lesson6
spec:
    ports:
        -  port: 8888
           targetPort: 8888
    selector:
        app: microfrontend-lesson6
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: microfrontend-lesson6
    namespace: lesson6
spec:
    replicas: 2
    selector:
        matchLabels:
            app: microfrontend-lesson6
    template:
        metadata:
            labels:
                app: microfrontend-lesson6
        spec:
            securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
            containers:
                -   name: microfrontend-lesson6
                    image: k3d-mashroomregistry.localhost:12345/microfrontend-lesson6:${VERSION}
                    imagePullPolicy: Always
                    env:
                        -   name: NODE_ENV
                            value: production
                    resources:
                        requests:
                            cpu: 100m
                            memory: 80Mi
                    ports:
                        -   containerPort: 8888
