version: "3.8"

x-mashroom-variables: &common-mashroom-variables
    NODE_ENV: production
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_PASSWORD: test
    LDAP_SERVER_URL: ldap://openLdap:10389
    LDAP_BIND_DN: cn=admin,dc=planetexpress,dc=com
    LDAP_BIND_PASSWORD: GoodNewsEveryone
    LOG_DEFAULT_LEVEL: info

services:
    mashroom1:
        build: ..
        ports:
            - "8080:8080"
        volumes:
            - ./log/node1:/var/log/mashroom
        environment:
            <<: *common-mashroom-variables
    mashroom2:
        build: ..
        ports:
            - "8081:8080"
        volumes:
            - ./log/node2:/var/log/mashroom
        environment:
            <<: *common-mashroom-variables
    mashroom3:
        build: ..
        ports:
            - "8082:8080"
        volumes:
            - ./log/node3:/var/log/mashroom
        environment:
            <<: *common-mashroom-variables
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
    openLdap:
        image: rroemhild/test-openldap:2.1
        ports:
            - "10389:10389"
    nginx:
        image: nginx:1.23.3
        ports:
            - "6060:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/ssl:/etc/nginx/ssl
            - ngnix_static_cache:/var/cache/nginx/proxy_cache

    # Optional Observability stuff
    loki:
        image: grafana/loki:2.7.3
        ports:
            - "3100:3100"
        volumes:
            - ./loki/config.yml:/etc/loki/config.yml
        command: -config.file=/etc/loki/config.yml
    promtail:
        image: grafana/promtail:2.7.3
        volumes:
            - ./log:/var/log/mashroom
            - ./promtail/config.yml:/etc/promtail/config.yml
        command: -config.file=/etc/promtail/config.yml
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/config.yml:/etc/prometheus/config.yml
        command:
            - "--config.file=/etc/prometheus/config.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
    grafana:
        image: grafana/grafana:8.2.6
        ports:
            - "3000:3000"
        volumes:
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        env_file:
            - ./grafana/config.monitoring
volumes:
    ngnix_static_cache:
